[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  '@rari-capital/=node_modules/@rari-capital/',
  'ds-test/=lib/ds-test/src/',
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@opengsn/=node_modules/@opengsn/',
]
fuzz_runs = 512
# See more config options https://github.com/gakonst/foundry/tree/master/config
